In [1]:
import numpy as np

In [13]:
ar1 = np.array(range(0,15)).reshape(5,3)
ar1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
ar1 = ar1 + 5
ar1

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
ar1[1:3,1:]

array([[ 9, 10],
       [12, 13]])

In [20]:
ar1[4,0] = 25
ar1[:,0]

array([ 5,  8, 11, 14, 25])

In [21]:
ar2 = np.random.randint(40,120,size=(3,4))
ar2

array([[ 62, 114, 103,  73],
       [ 48,  95,  81,  42],
       [ 55,  50,  44, 102]])

In [23]:
ar2 = ar2.astype(np.float)

In [25]:
np.min(ar2)

42.0

In [26]:
np.max(ar2)

114.0